# Generated by Django 4.2.3 on 2023-08-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="video",
            field=models.URLField(default="filme"),
        ),
        migrations.AlterField(
            model_name="episodio",
            name="video",
            field=models.URLField(default="episodio"),
        ),
        migrations.AlterField(
            model_name="filme",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ANIMACAO", "Animação"),
                    ("AVENTURA", "Aventura"),
                    ("OUTROS", "Outros"),
                    ("AÇÃO", "Ação"),
                ],
                max_length=15,
            ),
        ),
    ]
