# Generated by Django 4.2.3 on 2023-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filme", "0002_filme_video_alter_episodio_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filme",
            name="video",
        ),
        migrations.AlterField(
            model_name="episodio",
            name="video",
            field=models.URLField(),
        ),
    ]
